# Generated by Django 3.0.7 on 2020-07-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictype',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='是否私人保密'),
        ),
    ]
