# Generated by Django 3.0.7 on 2020-07-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0002_dynamictype_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictype',
            name='is_private',
        ),
        migrations.AddField(
            model_name='dynamictype',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
    ]
