# Generated by Django 3.0.8 on 2020-07-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictype',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.Mood', verbose_name='心情类型'),
        ),
    ]
