# Generated by Django 3.0.7 on 2020-07-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_auto_20200712_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictype',
            name='is_public',
        ),
        migrations.AddField(
            model_name='dynamic',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
    ]
