# Generated by Django 3.0.8 on 2020-07-21 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_dynamictype_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.DynamicType', verbose_name='标签'),
        ),
    ]
