# Generated by Django 3.0.8 on 2020-07-21 07:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_dynamic_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamictype',
            options={'ordering': ['-type_name']},
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
    ]
