# Generated by Django 3.0.8 on 2020-07-22 02:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0006_auto_20200721_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
